parameters:
    hw_basics.layoutservice.class: Hw\BasicsBundle\Twig\LayoutService
    hw_basics.menu.class: Hw\BasicsBundle\Menu\Menu
    hw_basics.menufactory.class: Hw\BasicsBundle\Menu\MenuFactory

services:
    hw_basics.menu.typeextension:
        class: Hw\BasicsBundle\Menu\TypeExtension
        arguments: ["@service_container", collection]
        public: false
    hw_basics.layoutservice:
        class: %hw_basics.layoutservice.class%
    hw_basics.menufactory:
        class: %hw_basics.menufactory.class%
        arguments: ["@hw_basics.layoutservice", "@hw_basics.menu.typeextension"]
    hw_basics.twig.hw_basics_extension:
        class: Hw\BasicsBundle\Twig\HwBasicsExtension
        arguments: ["@hw_basics.layoutservice"]
        tags:
            - { name: twig.extension }
